# Generated by Django 4.2.2 on 2023-11-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minorapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minorapi.book')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minorapi.user')),
            ],
        ),
    ]
