# Generated by Django 4.2.2 on 2023-11-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minorapi', '0002_user_issued'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issued',
        ),
    ]
