# Generated by Django 4.2.2 on 2023-11-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minorapi', '0003_delete_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='abc@gmail.com', max_length=50),
        ),
    ]
